//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pure.Data.i18n
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pure.Data.i18n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be non-chinese string. 的本地化字符串。
        /// </summary>
        public static string asciicoding_error
        {
            get
            {
                return ResourceManager.GetString("asciicoding_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid credit card number. 的本地化字符串。
        /// </summary>
        public static string CreditCardError
        {
            get
            {
                return ResourceManager.GetString("CreditCardError", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid china credit code. 的本地化字符串。
        /// </summary>
        public static string creditcode_error
        {
            get
            {
                return ResourceManager.GetString("creditcode_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid date format &apos;yyyy-MM-dd&apos;. 的本地化字符串。
        /// </summary>
        public static string date_error
        {
            get
            {
                return ResourceManager.GetString("date_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid domain . 的本地化字符串。
        /// </summary>
        public static string domain_error
        {
            get
            {
                return ResourceManager.GetString("domain_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid email address. 的本地化字符串。
        /// </summary>
        public static string email_error
        {
            get
            {
                return ResourceManager.GetString("email_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; should be empty. 的本地化字符串。
        /// </summary>
        public static string empty_error
        {
            get
            {
                return ResourceManager.GetString("empty_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; has a range of values which does not include &apos;{PropertyValue}&apos;. 的本地化字符串。
        /// </summary>
        public static string enum_error
        {
            get
            {
                return ResourceManager.GetString("enum_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; should be equal to &apos;{ComparisonValue}&apos;. 的本地化字符串。
        /// </summary>
        public static string equal_error
        {
            get
            {
                return ResourceManager.GetString("equal_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be {MaxLength} characters in length. You entered {TotalLength} characters. 的本地化字符串。
        /// </summary>
        public static string exact_length_error
        {
            get
            {
                return ResourceManager.GetString("exact_length_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be between {From} and {To} (exclusive). You entered {Value}. 的本地化字符串。
        /// </summary>
        public static string exclusivebetween_error
        {
            get
            {
                return ResourceManager.GetString("exclusivebetween_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be greater than &apos;{ComparisonValue}&apos;. 的本地化字符串。
        /// </summary>
        public static string greaterthan_error
        {
            get
            {
                return ResourceManager.GetString("greaterthan_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be greater than or equal to &apos;{ComparisonValue}&apos;. 的本地化字符串。
        /// </summary>
        public static string greaterthanorequal_error
        {
            get
            {
                return ResourceManager.GetString("greaterthanorequal_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid china ID Card number. 的本地化字符串。
        /// </summary>
        public static string idcard_error
        {
            get
            {
                return ResourceManager.GetString("idcard_error", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid china ID Card number. 的本地化字符串。
        /// </summary>
        public static string stringsafety_error
        {
            get
            {
                return ResourceManager.GetString("stringsafety_error", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be between {From} and {To}. You entered {Value}. 的本地化字符串。
        /// </summary>
        public static string inclusivebetween_error
        {
            get
            {
                return ResourceManager.GetString("inclusivebetween_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid ip mask. 的本地化字符串。
        /// </summary>
        public static string ipmask_error
        {
            get
            {
                return ResourceManager.GetString("ipmask_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid ip-v4. 的本地化字符串。
        /// </summary>
        public static string ipv4_error
        {
            get
            {
                return ResourceManager.GetString("ipv4_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid ip-v6. 的本地化字符串。
        /// </summary>
        public static string ipv6_error
        {
            get
            {
                return ResourceManager.GetString("ipv6_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be between {MinLength} and {MaxLength} characters. You entered {TotalLength} characters. 的本地化字符串。
        /// </summary>
        public static string length_error
        {
            get
            {
                return ResourceManager.GetString("length_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be less than &apos;{ComparisonValue}&apos;. 的本地化字符串。
        /// </summary>
        public static string lessthan_error
        {
            get
            {
                return ResourceManager.GetString("lessthan_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be less than or equal to &apos;{ComparisonValue}&apos;. 的本地化字符串。
        /// </summary>
        public static string lessthanorequal_error
        {
            get
            {
                return ResourceManager.GetString("lessthanorequal_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid china mobile number. 的本地化字符串。
        /// </summary>
        public static string mobile_error
        {
            get
            {
                return ResourceManager.GetString("mobile_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; should not be empty. 的本地化字符串。
        /// </summary>
        public static string notempty_error
        {
            get
            {
                return ResourceManager.GetString("notempty_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; should not be equal to &apos;{ComparisonValue}&apos;. 的本地化字符串。
        /// </summary>
        public static string notequal_error
        {
            get
            {
                return ResourceManager.GetString("notequal_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must not be empty. 的本地化字符串。
        /// </summary>
        public static string notnull_error
        {
            get
            {
                return ResourceManager.GetString("notnull_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be empty. 的本地化字符串。
        /// </summary>
        public static string null_error
        {
            get
            {
                return ResourceManager.GetString("null_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid china orgcode. 的本地化字符串。
        /// </summary>
        public static string orgcode_error
        {
            get
            {
                return ResourceManager.GetString("orgcode_error", resourceCulture);
            }
        }
        //public static string xss_error
        //{
        //    get
        //    {
        //        return ResourceManager.GetString("xss_error", resourceCulture);
        //    }
        //}
        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must start with a letter, the length of 6 to 18, can only contain letters, numbers and underscores. 的本地化字符串。
        /// </summary>
        public static string password_error
        {
            get
            {
                return ResourceManager.GetString("password_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified condition was not met for &apos;{PropertyName}&apos;. 的本地化字符串。
        /// </summary>
        public static string predicate_error
        {
            get
            {
                return ResourceManager.GetString("predicate_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos;  is not a valid china qq number. 的本地化字符串。
        /// </summary>
        public static string qqnumber_error
        {
            get
            {
                return ResourceManager.GetString("qqnumber_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not in the correct format. 的本地化字符串。
        /// </summary>
        public static string regex_error
        {
            get
            {
                return ResourceManager.GetString("regex_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; may not be more than {expectedPrecision} digits in total, with allowance for {expectedScale} decimals. {digits} digits and {actualScale} decimals were found. 的本地化字符串。
        /// </summary>
        public static string scale_precision_error
        {
            get
            {
                return ResourceManager.GetString("scale_precision_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must contain numbers, must contain lowercase or uppercase letters, must contain special symbols, at least 8 characters, and up to 30 characters. 的本地化字符串。
        /// </summary>
        public static string stronggpassword_error
        {
            get
            {
                return ResourceManager.GetString("stronggpassword_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid china telphone number. 的本地化字符串。
        /// </summary>
        public static string telphone_error
        {
            get
            {
                return ResourceManager.GetString("telphone_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid time format &apos;HH:mm:ss&apos;. 的本地化字符串。
        /// </summary>
        public static string time_error
        {
            get
            {
                return ResourceManager.GetString("time_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must be chinese string. 的本地化字符串。
        /// </summary>
        public static string unicodecoding_error
        {
            get
            {
                return ResourceManager.GetString("unicodecoding_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; must start with a letter, including letters, numbers, or underscores. 的本地化字符串。
        /// </summary>
        public static string username_error
        {
            get
            {
                return ResourceManager.GetString("username_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid website url. 的本地化字符串。
        /// </summary>
        public static string website_error
        {
            get
            {
                return ResourceManager.GetString("website_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{PropertyName}&apos; is not a valid zipcode. 的本地化字符串。
        /// </summary>
        public static string zipcode_error
        {
            get
            {
                return ResourceManager.GetString("zipcode_error", resourceCulture);
            }
        }

        public static string valid_success
        {
            get
            {
                return ResourceManager.GetString("valid_success", resourceCulture);
            }
        }

        public static string valid_fail
        {
            get
            {
                return ResourceManager.GetString("valid_fail", resourceCulture);
            }
        }
    }
}
